### ISSUE TITLE
Fix compilation on Debian Wheezy (older QGLviewer version)

### ISSUE THREAD

**Issue by eudoxos** [eudoxos/woodem#1]
Support for QGLViewer was removed in ef2891b, just put it back in place and test the build.

**Comment by eudoxos** [comment]
Should be fixed with 45809ae (and the commits before), tested in wheezy chroot. The bintuils-gold package must be installed. Please check.

Wheezy does not package minieigen, grab https://github.com/eudoxos/minieigen/ and run `python setup.py install`.

**Comment by eudoxos** [comment]
PS instead of compiling from source, you can build your own local debian package using the https://code.launchpad.net/~eudoxos/+archive/ubuntu/woo-daily PPA, see https://wiki.debian.org/CreatePackageFromPPA for procedure.

**Comment by gladk** [comment]
Vaclav,

if there is an interest to have minieigen on Wheezy, we can upload it into
wheezy-backports.
Just let me know.


Anton

2015-03-06 7:33 GMT+01:00 eudoxos <notifications@github.com>:

**Comment by eudoxos** [comment]
Hi Anton, that would be great. I always forget how influential friend I have. I will ask you (next week) how to properly tag revisions and so on, so that packaging is as easy as possible for you. Cheers!
