### ISSUE TITLE
Saving a box of ellipsoids and reloading it using ShapeBox seems not to work.

### ISSUE THREAD

**Issue by MaxWiebicke** [eudoxos/woodem#10]
after creating a box of ellipsoids and saving them into a textfile the terminal freezes. 
Furthermore they cannot be reloaded using 

sp=ShapePack()
sp.loadTxt('initial-state-dense-ellipsoids.txt')
sp.toDem(S,S.dem,mat)
S.dem.collectNodes()

**Comment by eudoxos** [comment]
Just to make it clear, it was that mass/inertia was not recomputed correctly, so there was zero mass/inertia resuling in positions being NaN in the next step.

**Comment by MaxWiebicke** [comment]
Thank you, Vaclav! It works now :)
