### ISSUE TITLE
Indroduce  stopAtTime 

### ISSUE THREAD

**Issue by friedrichaugust** [eudoxos/woodem#16]
A simulation shouls  be Stop at a defined simulation time point.
At the moment there is only the possibility to stop it with PyRunner(virtPeriod=stopTime,command='S.stop()')

A Scene property S.stopAtTime(stopTime) would be nice.

**Comment by eudoxos** [comment]
Fixed in fbff05ca44, see also https://github.com/eudoxos/woodem/blob/master/py/tests/core.py#L335 and https://woodem.eu/doc/woo.core.html#woo.core.Scene.stopAtTime .
