### ISSUE TITLE
Possible bug in Ice.cpp, line 73

### ISSUE THREAD

**Issue by GeekEqualsGood42** [eudoxos/woodem#28]
Hi Václav,

I believe there may be a typo in line 73 of Ice.cpp, which defines the conditions under which bonds break due to excessive torque in the twist direction. The twist limit is, as I recall, defined by the variable brkWR[0]. However, line 73 currently states that breakage occurs when the following is true:
(ph.isBrkBondX(2) && abs(Tw)>ph.brkWR[1])
meaning that Tw is apparently checked against the bend limit (brkWR[1]) instead. Is this indeed a bug?

Cheers,

Christopher Stanbridge

**Comment by eudoxos** [comment]
This issue was moved to woodem/woo#14
