### ISSUE TITLE
Option to export rods to ParaView as lines/minimal cells

### ISSUE THREAD

**Issue by GeekEqualsGood42** [eudoxos/woodem#29]
Hi Václav,

I greatly appreciate your having introduced the ability to export and visualize Woo rods in ParaView. We have already benefited quite a bit from this addition. However, constructing animations and videos from .vtk files containing rods is a little slow, seemingly for needless reasons, because of the level of detail that is required to render the hemispherical ends of the rods. With the default setting (subdiv = 16), there are 65 points and 128 cells in each rod. I can reduce this quite a bit by decreasing subdiv to 4, generating rods with square cross-sections, but the amount of data required for rendering the rods still isn't minimal.

I understand that the rod visualization code is based on the capsule visualization one, in which the spherical shape WOULD have been relevant; however, our developers wish to use rods as lines, and for our purpose the hemispheres do not matter. Might there be a way to simply export the rods to ParaView as single lines (e.g., by rendering them as minimal triangles with two of the points coincident)?

Cheers,
Christopher Stanbridge

**Comment by eudoxos** [comment]
This issue was moved to woodem/woo#21
